/* config.h.  Generated by configure.  */
/* These definitions are adjusted by `configure' automatically. */
/* Bruno Haible 16.7.1997 */


/* CPU */
#ifndef __i386__
/* #undef __i386__ */
#endif
#ifndef __m68k__
/* #undef __m68k__ */
#endif
#ifndef __mips__
/* #undef __mips__ */
#endif
#ifndef __mipsn32__
/* #undef __mipsn32__ */
#endif
#ifndef __mips64__
/* #undef __mips64__ */
#endif
#ifndef __sparc__
/* #undef __sparc__ */
#endif
#ifndef __sparc64__
/* #undef __sparc64__ */
#endif
#ifndef __alpha__
/* #undef __alpha__ */
#endif
#ifndef __hppa__
/* #undef __hppa__ */
#endif
#ifndef __arm__
/* #undef __arm__ */
#endif
#ifndef __rs6000__
/* #undef __rs6000__ */
#endif
#ifndef __m88k__
/* #undef __m88k__ */
#endif
#ifndef __convex__
/* #undef __convex__ */
#endif
#ifndef __ia64__
/* #undef __ia64__ */
#endif
#ifndef __x86_64__
#define __x86_64__ 1
#endif


/* compiler characteristics */

/* CL_VOID */
/* Define this as `char' if your compiler doesn't understand the void type. */
/* #undef void */


/* header files */

/* CL_STDC_HEADERS */
/* Define if you have the ANSI C header files
   <stdlib.h>, <stdarg.h>, <string.h>, <float.h>, <limits.h>. */
#define STDC_HEADERS 1

/* Define if you have <unistd.h>. */
#define HAVE_UNISTD_H 1

/* CL_OPENFLAGS */
/* Define if you need <sys/file.h> for using open() flags like O_RDWR. */
/* #undef OPEN_NEEDS_SYS_FILE_H */


/* typedefs */


/* functions and declarations */

/* CL_GETPAGESIZE */
/* Define if you have getpagesize(). */
#define HAVE_GETPAGESIZE 
/* Define as the return type of getpagesize(). */
#define RETGETPAGESIZETYPE int
/* Define if you have <sys/param.h>. */
/* #undef HAVE_SYS_PARAM_H */

/* CL_MACH_VM */
/* Define if you have the vm_allocate() and task_self() functions. */
/* #undef HAVE_MACH_VM */

/* CL_MMAP */
/* Define if you have <sys/mman.h> and the mmap() function. */
#define HAVE_MMAP 
/* Define if <sys/mman.h> defines MAP_ANON and mmaping with MAP_ANON works. */
#define HAVE_MMAP_ANON 
/* Define if <sys/mman.h> defines MAP_ANONYMOUS and mmaping with MAP_ANONYMOUS
   works. */
#define HAVE_MMAP_ANONYMOUS 
/* Define if mmaping of the special device /dev/zero works. */
#define HAVE_MMAP_DEVZERO 
/* Define if mmaping of the special device /dev/zero works,
   but only on addresses < 2^29. */
/* #undef HAVE_MMAP_DEVZERO_SUN4_29 */

/* CL_MPROTECT */
/* Define if you have the mprotect() function. */
#define HAVE_MPROTECT 1
/* Define if you have a working mprotect() function. */
#define HAVE_WORKING_MPROTECT 

/* CL_SHM */
/* Define if you have <sys/shm.h> and <sys/ipc.h> and shared memory works. */
#define HAVE_SHM 
/* Define if you also have <sys/sysmacros.h>. */
#define HAVE_SYS_SYSMACROS_H 1

/* CL_CODEEXEC */
/* Define if code in malloc'ed memory is executable. */
/* #undef CODE_EXECUTABLE */

/* AC_CHECK_HEADERS(sys/cachectl.h) */
/* Define if you have <sys/cachectl.h> */
/* #undef HAVE_SYS_CACHECTL_H */

/* AC_CHECK_HEADERS(sys/m88kbcs.h) */
/* Define if you have <sys/m88kbcs.h>. */
/* #undef HAVE_SYS_M88KBCS_H */

